# Write a github action workflow that will build my go lambda, thne zip it and upload it to an s3 bucked
name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.2

      - name: Buld
        run: go build -o function main.go

      - name: Zip
        run: zip function.zip function

      - name: Upload to lambda
        run: aws lambda update-function-code --function-name "rsvp-system" --zip-file fileb://lambda.zip" --region="eu-west-2"
